### ISSUE TITLE
Types for 'manualPagination', 'pageSize' and 'pageIndex' 

### ISSUE THREAD

**Issue by aroramayur** [ggascoigne/react-table-example#1]
The 'usePagination' API here - https://github.com/tannerlinsley/react-table/blob/master/docs/api/usePagination.md talks of 'initialState' and 'manualPagination' as two options that can be passed to useTable(options). 

Is there an example in TS?

The current type definitions don't have manualPagination , 'pageSize' and 'pageIndex' defined. 
`Property 'manualPagination' does not exist on type 'TableOptions<D>'. `

Should I be extending types here - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table

**Comment by ggascoigne** [comment]
You should look at the readme at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table.

Pay particular attention to how `UsePaginationOptions` is used.

**Comment by billsaysthis** [comment]
I created the d.ts file as specified and while my code compiles, at runtime I get a type error.

```  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    prepareRow,
    state: { pageIndex, pageSize },
    page,
    pageOptions,
    gotoPage,
    previousPage,
    nextPage,
    setPageSize,
    canPreviousPage,
    canNextPage,
  } = useTable({ columns, data, initialState: { pageIndex: 0, pageSize: 10 } }, usePagination)
```

Error output from Storybook (actually goes on longer but cropping at this size):
```ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx
./src/components/common/Table/Table.tsx
[tsl] ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx(33,14)
      TS2339: Property 'pageIndex' does not exist on type 'TableState<object>'.
ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx
./src/components/common/Table/Table.tsx
[tsl] ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx(33,25)
      TS2339: Property 'pageSize' does not exist on type 'TableState<object>'.
ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx
./src/components/common/Table/Table.tsx
[tsl] ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx(34,5)
      TS2339: Property 'page' does not exist on type 'TableInstance<object>'.
ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx
./src/components/common/Table/Table.tsx
[tsl] ERROR in /Users/billlazar/dev/react-acton-ui/src/components/common/Table/Table.tsx(35,5)
      TS2339: Property 'pageOptions' does not exist on type 'TableInstance<object>'.
```

**Comment by ggascoigne** [comment]
If tsc is happy with the code, then I'd assume some problem setting up storybook so that it sees your types file.

**Comment by billsaysthis** [comment]
okay -- I don't see a close button for this but feel free to close.
