### ISSUE TITLE
Property 'index' does not exist on type 'ColumnInstance<T>' with "@types/react-table": "7.0.29"

### ISSUE THREAD

**Issue by michaelbdavid** [ggascoigne/react-table-example#4]
Hey @ggascoigne ,

I'm pretty new to react/ts world.  I've been using one of your examples to modal creating tables and I've run into issues with the latest version of @types/react-table": "7.0.29" with react-table "react-table": "^7.6.3"

Inside your Table component im seeing:

Property 'index' does not exist on type 'ColumnInstance<T>'.  TS2339

    52 | 
    53 | function DefaultColumnFilter<T extends Record<string, unknown>>({
  > 54 |     column: { id, index, filterValue, setFilter, render, parent },
       |                   ^
    55 | }: FilterProps<T>) {
    56 |     const [value, setValue] = React.useState(filterValue || '');
    57 |     const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {

When I downgrade to  "@types/react-table": "7.0.28"  I'm able to build again but I'd like to be running on lastest and greatest if possible.

Any help is appreciated,
Michael

**Comment by ggascoigne** [comment]
index was removed from the types because it no longer existed.

Check out https://github.com/ggascoigne/react-table-example/blob/master/src/Table/Table.tsx#L56, you'll see that my example DefaultColumnFilter has changed to reflect this.

**Comment by michaelbdavid** [comment]
Thank you.  I was just looking at that.  Any other changes I need to pay attention to?

**Comment by ggascoigne** [comment]
Not if it's compiling :)

There were a couple of other small changes to do with values that might be undefined, but if it's compiling then you aren't likely to notice anything different.

**Comment by michaelbdavid** [comment]
Thx Guy!  Back up and running.

**Comment by ggascoigne** [comment]
np :)
