### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by samueldervis** [ggascoigne/react-table-example#6]
Typescript is complaining that isGrouped does not exist on type cell

https://github.com/ggascoigne/react-table-example/blob/10c98261ad678ec0a9530597e3f1fd8d90657b2b/src/Table/Table.tsx#L249

```json
"typescript": "^4.2.4",
"react-table": "^7.6.3",
"@types/react-table": "^7.7.1",
"@material-ui/core": "^4.11.4",
"@material-ui/icons": "^4.11.2",
```

**Comment by ggascoigne** [comment]
I just checked out the repo, changed to the versions that you listed and cannot reproduce the problem.   I'd look at the other changes that you've made.
